modLoader="javafml"
loaderVersion="[34,)"
license="GNU General Public License v3.0"


[[mods]]
modId="rec"
version="0.2.0"
displayName="Reclusiarch Mod"
updateJSONURL="http://myurl.me/"
displayURL="http://example.com/"
logoFile="examplemod.png"
credits="Mcjty, TurtyWurty"
authors="Bixel"

description='''
This mod adds inspired new Ores and ways of processing the Ores
'''

[[dependencies.rec]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    # versionRange="[32,)" 1.16.1
    versionRange="[34,)" #mandatory
    ordering="NONE"
    side="BOTH"
